### ISSUE TITLE
[BUG] close_session function throws ErrType 100 on macOS Monterey (Intel Processor) when save_on_close is set to False

### ISSUE THREAD

**Issue by juanpablobello** [iluvcapra/py-ptsl#45]
**Description:**
The `close_session` function accepts one boolean parameter, `save_on_close`. When the parameter is set to `True`, the session closes as expected. However, when the parameter is set to `False`, the following error occurs:
`ErrType 100: PT_UnknownError (save_on_close)`

The implemented tests for the function do not report any issues when using either `True` or `False`, but the error consistently appears during actual usage with `False`.

**To Reproduce**
```python

from py_ptsl import open_engine
from ptsl import PTSL_pb2 as pt

with open_engine(company_name="py-ptsl", application_name=sys.argv[0]) as engine:
    # This works as expected
    engine.close_session(save_on_close=True)
    
    # This throws the error: ErrType 100: PT_UnknownError (save_on_close)
    engine.close_session(save_on_close=False)

```

**Expected behavior**
When calling the `close_session` function with `save_on_close=False`, the session should close without saving and without throwing any errors.

**Screenshots**
Here is the error traceback:

```python

Traceback (most recent call last):
  File "/Users/jp/Desktop/python_work/app_logic.py", line 312, in <module>
    engine.close_session(save_on_close=False)
  File "/Users/jp/Desktop/python_work/py-ptsl/ptsl/engine.py", line 211, in close_session
    self.client.run(op)
  File "/Users/jp/Desktop/python_work/py-ptsl/ptsl/client.py", line 161, in run
    raise CommandError(command_errors.errors)
ptsl.errors.CommandError: ErrType 100: PT_UnknownError (save_on_close)

```

**Platform:**
- Operating System: macOS Monterey 12.7.6 (Intel Processor)
- Pro Tools Version: Pro Tools Studio 2024.6.0

**Additional context**
I encountered this bug while implementing the `SetTrackState` commands in the Engine Class (introduced in the Pro Tools 2024.6). So far, I have tested the following commands, and they exhibit the same behavior as `close_session` when setting their respective states to` False`:

- `SetTrackSoloState`
- `SetTrackSoloSafeState`
- `SetTrackMuteState`
- `SetTrackRecordEnableState`
- ` SetTrackRecordSafeEnableState`
- `SetTrackInputMonitorState`

-----

I'm having lots of fun with the library! Thanks for all the awesome work you’ve put into it.

**Comment by iluvcapra** [comment]
Im pretty sure this has to do with Boolean handling in the protobuf library, I was having big problems with this in Swift. 

I'm going to wait until the next release and take a look at this.

**Comment by StephenMachete** [comment]
It's kind of guessing (since i'm a noob and don't know how to see the actual json) but i think i got the problem kinda pinned down.
I figured if setting "always_print_fields_with_no_presence" in the client to true it works:
```
request_body_json = json_format.MessageToJson(operation.request,
                                          always_print_fields_with_no_presence=True,
                                          preserving_proto_field_name=True)
```
I guess this option prints all "unset values" into the json.
The SDK treats "empy values" and "no value send" differently. For example:
If you don't send any value for the number attribute of CreateMemoryLocation, with the always_print option ON, ProTools creates a Marker with default number 32000.
But when you don't send any value for the number attribute of CreateMemoryLocation, with the always_print option OFF, ProTools creates a Marker with the next available number counting up from 1.(Just like manually creating a marker)
On the other hand if you send no value for most? booleans with option off, PT expects some value and has no "default" and throws an error. With the option turned on, PT defaults the "empty value" to False.

I think protobuf doesnt treat "default value" and "no value" differently. If False is the default value, protobuf just sends nothing, therefor if the option is turned off, nothing is printed into the json and PT behaves like descibed above. See:
https://stackoverflow.com/questions/68507484/how-to-collect-all-boolean-false-true-values-present-in-grpc-protobuf-request-in

**Comment by iluvcapra** [comment]
This looks right, this option field looks new, I don't think I've seen it before.

The protobuf implementation has been very flaky generally because of disagreement over things like how to handle missing fields between the python implementation and the C++ one Avid is using.

**Comment by iluvcapra** [comment]
Now that 2024.10 is out we can start transitioning over to sending JSON requests instead of using ProtoBuf to serialize the parameters, which should be a lot less error-prone but it will require a lot of re-engineering.
